### ISSUE TITLE
Merge zkalc backend 

### ISSUE THREAD

**Issue by tumberger** [zkCollective/zk-Harness#17]
Merge with the [zkalc](zka.lc) backend for arithmetic / curve operations

- [ ] arkworks benchmarks
- [ ] blstrs benchmarks
- [ ] curve25519-dalek benchmarks
- [ ] pasta curves (halo2, zcash)
- [ ] zkcrypto
- [ ] gnark - the zkalc way (maintenance of benchmarks on gnark side)
- [ ] config specification
- [ ] compliance with log format + memory benchmarks (parser of criterion output?)

**Comment by StefanosChaliasos** [comment]
We keep track of this one here: #34
