### ISSUE TITLE
introduce memory usage benchmarks for Rust-based frameworks

### ISSUE THREAD

**Issue by bingcicle** [zkCollective/zk-Harness#24]
In private conversations with @tumberger we discussed 2 ways of measuring memory usage:

1) **in-language memory benchmarks**: this would require most likely require usage of [jemalloc](https://github.com/jemalloc/jemalloc), which means we need to depend on libc directly.

2) **external tools**: we could also use `/usr/bin/time` or something like `valgrind`.

If we decide on 2), the logic between the test runner<>benchmarks would have to be separated, since in the current runner we are doing other tasks like writing to CSV, etc. which means we may not get the most accurate results.

**Comment by StefanosChaliasos** [comment]
We will probably need to go with the second option so that we can use the same tooling across all frameworks. Hence, we will need separate runners per phase.

**Comment by StefanosChaliasos** [comment]
In #32, we use `time` to perform the measurement.
