### ISSUE TITLE
Matrix Multiplication Groth16 and Plonk Integration

### ISSUE THREAD

**Issue by CptKincaid** [zkCollective/zk-Harness#46]
Hello, I am an UG research student working on a ZKP protocol project. As part of the project I figured out how to properly integrate Groth16 and Plonk Matrix Multiplication functions for 1x2, 2x2, 4x2, 8x2, and 16x2. They work properly and as intended and I would like to contribute this to the harness project since it has been so helpful for me in my research/project! This would be my first contribution however and I am not sure if its up to what is required to make a contribution. 

The zip contains the files i changed/added/created/poorly coded

I will be moving on from making anymore additions to it as I am now moving on to a different part of the project but I will try to assist if i can. I am a very novice coder :) Hope this helps anyone who may need it!

[MxMultFiles.zip](https://github.com/user-attachments/files/15779031/MxMultFiles.zip)

**Comment by tumberger** [comment]
Hi @CptKincaid , 

Happy to hear this repo is helpful in your project! No worries about being a novice. The usual flow for contribution in Github requires you to create a ``Pull Request``.

This can be done as follows:

1. Click the "Fork" button to create your own copy.
2. Run `git clone <your-fork-url>`.
3. Run `git checkout -b <new-branch-name>`.
4. **Make Changes:**
   - Edit the files as needed.
   - Stage your changes with `git add .`.
   - Commit your changes with `git commit -m "Description of changes"`.
5. **Push Changes:**
   - Run `git push origin <new-branch-name>`.
6. **Create the Pull Request:**
   - Go to your forked repository on GitHub.
   - Click the "Compare & pull request" button.
   - Add a title and description for your PR.
   - Click "Create pull request".
