### ISSUE TITLE
Provide Nix build code

### ISSUE THREAD

**Issue by morganthomas** [zkCollective/zk-Harness#6]
Hi! I want Nix build code so that I can more easily build this project and it can more easily be reproduced on other people's machines. I am interested in doing this issue as part of the Berkeley ZK hackathon.

**Comment by StefanosChaliasos** [comment]
Hi, thanks for bringing this up. This is a feature we thought about as well! Our initial thought was to use Docker, but we can have both. I think a nice start will be to run gnark through nix and/or Docker. When further frameworks are integrated during the course of the hackathon, it would be great if you could add support for those as well. The final allocation of dedicated & self-selected tasks will be done on the 12th of March in the hackathon; we will reach out again then for prize information, etc! Until then, please feel free to go ahead and fork the repo if you already want to start building!

**Comment by StefanosChaliasos** [comment]
#7
