### ISSUE TITLE
`time` command: what version works with these options?

### ISSUE THREAD

**Issue by morganthomas** [zkCollective/zk-Harness#8]
I cannot reproduce the `circom` benchmarks on my end because `/usr/bin/time` is not behaving as expected for me; it does not recognize the options `-h -l -o`. What version of `time` works with the `circom` benchmarks script? @StefanosChaliasos

**Comment by StefanosChaliasos** [comment]
Hi, thanks for pointing that out. This #9 should fix this error.

**Comment by StefanosChaliasos** [comment]
@morganthomas, could you verify that you can now run the script? If that is the case please close this issue.

**Comment by morganthomas** [comment]
Yup, that does the trick! Thanks, @StefanosChaliasos !
